Allow access to legacy hash algo for storybook
Storybook requires an old hash (not sure which one).

Running 'yarn run storybook' results in the following error with
Node.js v20.18.1 on ubuntu 22.04.1:

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:79:19)
    at Object.createHash (node:crypto:139:10)
    at module.exports (/workspaces/iaux/packages/ia-components/node_modules/@storybook/core/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/workspaces/iaux/packages/ia-components/node_modules/@storybook/core/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/workspaces/iaux/packages/ia-components/node_modules/@storybook/core/node_modules/webpack/lib/NormalModule.js:471:10)
    at /workspaces/iaux/packages/ia-components/node_modules/@storybook/core/node_modules/webpack/lib/NormalModule.js:503:5
    at /workspaces/iaux/packages/ia-components/node_modules/@storybook/core/node_modules/webpack/lib/NormalModule.js:358:12
    at /workspaces/iaux/packages/ia-components/node_modules/@storybook/core/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/workspaces/iaux/packages/ia-components/node_modules/@storybook/core/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at /workspaces/iaux/packages/ia-components/node_modules/@storybook/core/node_modules/loader-runner/lib/LoaderRunner.js:205:4
    at /workspaces/iaux/packages/ia-components/node_modules/@storybook/core/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:85:15
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  opensslErrorStack: [
    'error:03000086:digital envelope routines::initialization error',
    'error:0308010C:digital envelope routines::unsupported'
  ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

This commit resolves this error by allowing node to use the legacy hash algo.